-- Table: public.inventory

-- DROP TABLE IF EXISTS public.inventory;

CREATE TABLE IF NOT EXISTS public.inventory
(
    discord_id character varying COLLATE pg_catalog."default" NOT NULL,
    money integer DEFAULT 0,
    "poke-ball" integer DEFAULT 0,
    "great-ball" integer DEFAULT 0,
    "ultra-ball" integer DEFAULT 0,
    "master-ball" integer DEFAULT 0,
    potion integer DEFAULT 0,
    "super-potion" integer DEFAULT 0,
    "hyper-potion" integer DEFAULT 0,
    "max-potion" integer DEFAULT 0,
    revive integer DEFAULT 0,
    "full-restore" integer DEFAULT 0,
    repel integer DEFAULT 0,
    "max-repel" integer DEFAULT 0,
    awakening integer DEFAULT 0,
    "escape-rope" integer DEFAULT 0,
    "full-heal" integer DEFAULT 0,
    "ice-heal" integer DEFAULT 0,
    "burn-heal" integer DEFAULT 0,
    "paralyze-heal" integer DEFAULT 0,
    antidote integer DEFAULT 0,
    calcium integer DEFAULT 0,
    carbos integer DEFAULT 0,
    "coin-case" integer DEFAULT 0,
    "dire-hit" integer DEFAULT 0,
    "fresh-water" integer DEFAULT 0,
    "hp-up" integer DEFAULT 0,
    lemonade integer DEFAULT 0,
    elixir integer DEFAULT 0,
    "max-elixir" integer DEFAULT 0,
    "max-ether" integer DEFAULT 0,
    ether integer DEFAULT 0,
    nugget integer DEFAULT 0,
    "poke-doll" integer DEFAULT 0,
    "pp-up" integer DEFAULT 0,
    "soda-pop" integer DEFAULT 0,
    "town-map" integer DEFAULT 0,
    "x-accuracy" integer DEFAULT 0,
    "x-defense" integer DEFAULT 0,
    "x-sp-atk" integer DEFAULT 0,
    "x-speed" integer DEFAULT 0,
    "super-repel" integer DEFAULT 0,
    "fire-stone" integer DEFAULT 0,
    "water-stone" integer DEFAULT 0,
    "thunder-stone" integer DEFAULT 0,
    "leaf-stone" integer DEFAULT 0,
    "moon-stone" integer DEFAULT 0,
    "x-attack" integer DEFAULT 0,
    "x-sp-def" integer DEFAULT 0,
    "link-cable" integer DEFAULT 0,
    "game-shark" integer DEFAULT 0,
    iron integer DEFAULT 0,
    protein integer DEFAULT 0,
    "TM01" integer DEFAULT 0,
    "TM02" integer DEFAULT 0,
    "TM03" integer DEFAULT 0,
    "TM04" integer DEFAULT 0,
    "TM05" integer DEFAULT 0,
    "TM06" integer DEFAULT 0,
    "TM07" integer DEFAULT 0,
    "TM08" integer DEFAULT 0,
    "TM09" integer DEFAULT 0,
    "TM10" integer DEFAULT 0,
    "TM11" integer DEFAULT 0,
    "TM12" integer DEFAULT 0,
    "TM13" integer DEFAULT 0,
    "TM14" integer DEFAULT 0,
    "TM15" integer DEFAULT 0,
    "TM16" integer DEFAULT 0,
    "TM17" integer DEFAULT 0,
    "TM18" integer DEFAULT 0,
    "TM19" integer DEFAULT 0,
    "TM20" integer DEFAULT 0,
    "TM21" integer DEFAULT 0,
    "TM22" integer DEFAULT 0,
    "TM23" integer DEFAULT 0,
    "TM24" integer DEFAULT 0,
    "TM25" integer DEFAULT 0,
    "TM26" integer DEFAULT 0,
    "TM27" integer DEFAULT 0,
    "TM28" integer DEFAULT 0,
    "TM29" integer DEFAULT 0,
    "TM30" integer DEFAULT 0,
    "TM31" integer DEFAULT 0,
    "TM32" integer DEFAULT 0,
    "TM33" integer DEFAULT 0,
    "TM34" integer DEFAULT 0,
    "TM35" integer DEFAULT 0,
    "TM36" integer DEFAULT 0,
    "TM37" integer DEFAULT 0,
    "TM38" integer DEFAULT 0,
    "TM39" integer DEFAULT 0,
    "TM40" integer DEFAULT 0,
    "TM41" integer DEFAULT 0,
    "TM42" integer DEFAULT 0,
    "TM43" integer DEFAULT 0,
    "TM44" integer DEFAULT 0,
    "TM45" integer DEFAULT 0,
    "TM46" integer DEFAULT 0,
    "TM47" integer DEFAULT 0,
    "TM48" integer DEFAULT 0,
    "TM49" integer DEFAULT 0,
    "TM50" integer DEFAULT 0,
    CONSTRAINT inventory_pkey PRIMARY KEY (discord_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.inventory
    OWNER to redbot;